trigger:

- main
- develop
pr:
  autoCancel: true
  branches:
    include:
    - main

variables:
  - group: Azure-Devops-Extensions-Variables-Validate

name: $(BuildID)

pool:
  vmImage: 'windows-latest'

steps:
- task: validateVariablesTask@0
  inputs:
    warnOrError: 'Error'

- task: Npm@1
  inputs:
    command: 'install'

- task: TfxInstaller@3
  inputs:
    version: 'v0.9.x'

- task: PowerShell@2
  displayName: Debug vars
  inputs:
    targetType: 'inline'
    script: |
      Get-ChildItem env:* | ForEach-Object {
            Write-Host ("Variable {0}: {1}" -f $_.Name, $_.Value) 
      }

- task: PowerShell@2
  displayName: 'Build Test'
  inputs:
    filePath: 'build.ps1'
    arguments: '-Config Test -VersionMajor $(VersionMajor) -VersionMinor $(VersionMinor) -VersionPatch $(Build.BuildNumber) -Clean $True'
    pwsh: true

- task: CopyFiles@2
  displayName: 'Copy Test Files'
  inputs:
    SourceFolder: '$(agent.builddirectory)'
    Contents: '**\*.vsix'
    TargetFolder: '$(build.artifactstagingdirectory)'
    CleanTargetFolder: true
    flattenFolders: true

- task: PowerShell@2
  displayName: 'Build Prod'
  inputs:
    filePath: 'build.ps1'
    arguments: '-Config Prod -VersionMajor $(VersionMajor) -VersionMinor $(VersionMinor) -VersionPatch $(Build.BuildNumber) -Clean $False'
    pwsh: true

- task: CopyFiles@2
  displayName: 'Copy Prod Files'
  inputs:
    SourceFolder: '$(agent.builddirectory)'
    Contents: '**\*.vsix'
    TargetFolder: '$(build.artifactstagingdirectory)'
    flattenFolders: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: PowerShell@2
  displayName: 'Publish Test Version to MarketPlace'
  inputs:
    targetType: 'inline'
    script: |
      $files = get-childitem bjh1977.validateVariablesTasksTesting*.vsix
      $filename = $files.name

      Write-Host "Filename is $filename, token is '$(Token)'"

      &tfx extension publish --vsix $filename --token $(Token) --share-with bjh-consulting --auth-type pat
    pwsh: true
    workingDirectory: '$(build.artifactstagingdirectory)'